- name: "Carsten Node Ansible Playbook"
  hosts: default
  become: yes
  tasks:
    - name: Upgrade apt dependencies
      apt:
        update_cache: yes
        upgrade: safe

    - name: Install apt dependencies
      apt:
        name:
          - ca-certificates
          - lrzsz
          - rsync
          - git
          - vim
          - htop
          - jq
          - unzip
          - curl
          - python3
          - python3-venv
          - python3-pip
        state: present
        force: yes
        update_cache: yes

    - name: Clone carsten repo
      git:
        repo: https://github.com/erdos4d/carsten.git
        dest: /carsten

    - name: Install pip dependencies
      pip:
        requirements: /carsten/requirements.txt

    - name: Copy server folder
      synchronize:
        src: ./server
        dest: /
        recursive: yes
        rsync_opts:
          - "--chmod=F777"
          - "--chmod=D777"

    - name: Move systemd service file
      copy:
        src: /server/init.service
        dest: /etc/systemd/system/init.service
        remote_src: yes
        owner: root
        group: root
        mode: '0644'

    - name: Ensure init service is enabled and not masked
      systemd:
        state: stopped
        name: init
        enabled: yes
        masked: no
        daemon_reload: yes

